<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="43559" started-at="2018-12-20T07:25:16Z" finished-at="2018-12-20T07:25:59Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="43559" started-at="2018-12-20T07:25:16Z" finished-at="2018-12-20T07:25:59Z">
      <class name="com.ksrtc.Tests.SigninTest">
        <test-method status="PASS" signature="getlogger()[pri:0, instance:com.ksrtc.Tests.SigninTest@5c3bd550]" name="getlogger" is-config="true" duration-ms="119" started-at="2018-12-20T12:55:16Z" finished-at="2018-12-20T12:55:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getlogger -->
        <test-method status="PASS" signature="setup()[pri:0, instance:com.ksrtc.Tests.SigninTest@5c3bd550]" name="setup" is-config="true" duration-ms="36278" started-at="2018-12-20T12:55:16Z" finished-at="2018-12-20T12:55:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="TC002()[pri:0, instance:com.ksrtc.Tests.SigninTest@5c3bd550]" name="TC002" duration-ms="214" started-at="2018-12-20T12:55:52Z" finished-at="2018-12-20T12:55:52Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.ksrtc.helper.Helpermethods.signin(Helpermethods.java:37)
	at com.ksrtc.Tests.SigninTest.TC002(SigninTest.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC002 -->
        <test-method status="PASS" signature="close()[pri:0, instance:com.ksrtc.Tests.SigninTest@5c3bd550]" name="close" is-config="true" duration-ms="7045" started-at="2018-12-20T12:55:52Z" finished-at="2018-12-20T12:55:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close -->
      </class> <!-- com.ksrtc.Tests.SigninTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
